version: "3.7"
services:
  jekyll:
    container_name: jekyll_serve
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose --livereload 
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll